class MountainData {
  final double startAngle;
  final double endAngle;
  final String mountain;
  final String bagua;
  final String houseType;
  final String description;

  const MountainData({
    required this.startAngle,
    required this.endAngle,
    required this.mountain,
    required this.bagua,
    required this.houseType,
    required this.description,
  });
}

class XiantianBaguaData {
  final double startAngle;
  final double endAngle;
  final String bagua;
  final String luoshuNumber;

  const XiantianBaguaData({
    required this.startAngle,
    required this.endAngle,
    required this.bagua,
    required this.luoshuNumber,
  });
}

class DragonData {
  final double startAngle;
  final double endAngle;
  final String dragon;

  const DragonData({
    required this.startAngle,
    required this.endAngle,
    required this.dragon,
  });
}

class GoldData {
  final double startAngle;
  final double endAngle;
  final String gold;

  const GoldData({
    required this.startAngle,
    required this.endAngle,
    required this.gold,
  });
}

class Renpan24Data {
  final double startAngle;
  final double endAngle;
  final String mountain;

  const Renpan24Data({
    required this.startAngle,
    required this.endAngle,
    required this.mountain,
  });
}

const List<MountainData> mountainDatas = [
  MountainData(
    startAngle: 337.5,
    endAngle: 352.5,
    mountain: '壬',
    bagua: '坎',
    houseType: '坎宅',
    description: '水旺，利於智慧同事業，但需防意外。',
  ),
  MountainData(
    startAngle: 352.5,
    endAngle: 7.5,
    mountain: '子',
    bagua: '坎',
    houseType: '坎宅',
    description: '水旺，利於智慧同事業，但需防意外。',
  ),
  MountainData(
    startAngle: 7.5,
    endAngle: 22.5,
    mountain: '癸',
    bagua: '坎',
    houseType: '坎宅',
    description: '水旺，利於智慧同事業，但需防意外。',
  ),
  MountainData(
    startAngle: 22.5,
    endAngle: 37.5,
    mountain: '丑',
    bagua: '艮',
    houseType: '艮宅',
    description: '山穩，利於穩定，但易阻滯。',
  ),
  MountainData(
    startAngle: 37.5,
    endAngle: 52.5,
    mountain: '艮',
    bagua: '艮',
    houseType: '艮宅',
    description: '山穩，利於穩定，但易阻滯。',
  ),
  MountainData(
    startAngle: 52.5,
    endAngle: 67.5,
    mountain: '寅',
    bagua: '艮',
    houseType: '艮宅',
    description: '山穩，利於穩定，但易阻滯。',
  ),
  MountainData(
    startAngle: 67.5,
    endAngle: 82.5,
    mountain: '甲',
    bagua: '震',
    houseType: '震宅',
    description: '雷動，利於進取，但防動盪。',
  ),
  MountainData(
    startAngle: 82.5,
    endAngle: 97.5,
    mountain: '卯',
    bagua: '震',
    houseType: '震宅',
    description: '雷動，利於進取，但防動盪。',
  ),
  MountainData(
    startAngle: 97.5,
    endAngle: 112.5,
    mountain: '乙',
    bagua: '震',
    houseType: '震宅',
    description: '雷動，利於進取，但防動盪。',
  ),
  MountainData(
    startAngle: 112.5,
    endAngle: 127.5,
    mountain: '辰',
    bagua: '巽',
    houseType: '巽宅',
    description: '風順，利於財富，但易散氣。',
  ),
  MountainData(
    startAngle: 127.5,
    endAngle: 142.5,
    mountain: '巽',
    bagua: '巽',
    houseType: '巽宅',
    description: '風順，利於財富，但易散氣。',
  ),
  MountainData(
    startAngle: 142.5,
    endAngle: 157.5,
    mountain: '巳',
    bagua: '巽',
    houseType: '巽宅',
    description: '風順，利於財富，但易散氣。',
  ),
  MountainData(
    startAngle: 157.5,
    endAngle: 172.5,
    mountain: '丙',
    bagua: '离',
    houseType: '离宅',
    description: '光明，利於名聲，但易燥熱。',
  ),
  MountainData(
    startAngle: 172.5,
    endAngle: 187.5,
    mountain: '午',
    bagua: '离',
    houseType: '离宅',
    description: '光明，利於名聲，但易燥熱。',
  ),
  MountainData(
    startAngle: 187.5,
    endAngle: 202.5,
    mountain: '丁',
    bagua: '离',
    houseType: '离宅',
    description: '光明，利於名聲，但易燥熱。',
  ),
  MountainData(
    startAngle: 202.5,
    endAngle: 217.5,
    mountain: '未',
    bagua: '坤',
    houseType: '坤宅',
    description: '大地包容，利於和諧，但易積負能量。',
  ),
  MountainData(
    startAngle: 217.5,
    endAngle: 232.5,
    mountain: '坤',
    bagua: '坤',
    houseType: '坤宅',
    description: '大地包容，利於和諧，但易積負能量。',
  ),
  MountainData(
    startAngle: 232.5,
    endAngle: 247.5,
    mountain: '申',
    bagua: '坤',
    houseType: '坤宅',
    description: '大地包容，利於和諧，但易積負能量。',
  ),
  MountainData(
    startAngle: 247.5,
    endAngle: 262.5,
    mountain: '庚',
    bagua: '兑',
    houseType: '兑宅',
    description: '喜悅，利於人際，但防口舌。',
  ),
  MountainData(
    startAngle: 262.5,
    endAngle: 277.5,
    mountain: '酉',
    bagua: '兑',
    houseType: '兑宅',
    description: '喜悅，利於人際，但防口舌。',
  ),
  MountainData(
    startAngle: 277.5,
    endAngle: 292.5,
    mountain: '辛',
    bagua: '兑',
    houseType: '兑宅',
    description: '喜悅，利於人際，但防口舌。',
  ),
  MountainData(
    startAngle: 292.5,
    endAngle: 307.5,
    mountain: '戌',
    bagua: '乾',
    houseType: '乾宅',
    description: '天權威，利於領導，但防孤寡。',
  ),
  MountainData(
    startAngle: 307.5,
    endAngle: 322.5,
    mountain: '乾',
    bagua: '乾',
    houseType: '乾宅',
    description: '天權威，利於領導，但防孤寡。',
  ),
  MountainData(
    startAngle: 322.5,
    endAngle: 337.5,
    mountain: '亥',
    bagua: '乾',
    houseType: '乾宅',
    description: '天權威，利於領導，但防孤寡。',
  ),
];

const List<XiantianBaguaData> xiantianBaguaDatas = [
  XiantianBaguaData(
    startAngle: 337.5,
    endAngle: 22.5,
    bagua: '坤',
    luoshuNumber: '二',
  ),
  XiantianBaguaData(
    startAngle: 22.5,
    endAngle: 67.5,
    bagua: '震',
    luoshuNumber: '三',
  ),
  XiantianBaguaData(
    startAngle: 67.5,
    endAngle: 112.5,
    bagua: '离',
    luoshuNumber: '九',
  ),
  XiantianBaguaData(
    startAngle: 112.5,
    endAngle: 157.5,
    bagua: '兑',
    luoshuNumber: '七',
  ),
  XiantianBaguaData(
    startAngle: 157.5,
    endAngle: 202.5,
    bagua: '乾',
    luoshuNumber: '六',
  ),
  XiantianBaguaData(
    startAngle: 202.5,
    endAngle: 247.5,
    bagua: '巽',
    luoshuNumber: '四',
  ),
  XiantianBaguaData(
    startAngle: 247.5,
    endAngle: 292.5,
    bagua: '坎',
    luoshuNumber: '一',
  ),
  XiantianBaguaData(
    startAngle: 292.5,
    endAngle: 337.5,
    bagua: '艮',
    luoshuNumber: '八',
  ),
];

const List<DragonData> dragonDatas = [
  DragonData(startAngle: 0.0, endAngle: 5.0, dragon: '丙子'),
  DragonData(startAngle: 5.0, endAngle: 10.0, dragon: '丁丑'),
  DragonData(startAngle: 10.0, endAngle: 15.0, dragon: '戊寅'),
  DragonData(startAngle: 15.0, endAngle: 20.0, dragon: '己卯'),
  DragonData(startAngle: 20.0, endAngle: 25.0, dragon: '庚辰'),
  DragonData(startAngle: 25.0, endAngle: 30.0, dragon: '辛巳'),
  DragonData(startAngle: 30.0, endAngle: 35.0, dragon: '壬午'),
  DragonData(startAngle: 35.0, endAngle: 40.0, dragon: '癸未'),
  DragonData(startAngle: 40.0, endAngle: 45.0, dragon: '甲申'),
  DragonData(startAngle: 45.0, endAngle: 50.0, dragon: '乙酉'),
  DragonData(startAngle: 50.0, endAngle: 55.0, dragon: '丙戌'),
  DragonData(startAngle: 55.0, endAngle: 60.0, dragon: '丁亥'),
  DragonData(startAngle: 60.0, endAngle: 65.0, dragon: '戊子'),
  DragonData(startAngle: 65.0, endAngle: 70.0, dragon: '己丑'),
  DragonData(startAngle: 70.0, endAngle: 75.0, dragon: '庚寅'),
  DragonData(startAngle: 75.0, endAngle: 80.0, dragon: '辛卯'),
  DragonData(startAngle: 80.0, endAngle: 85.0, dragon: '壬辰'),
  DragonData(startAngle: 85.0, endAngle: 90.0, dragon: '癸巳'),
  DragonData(startAngle: 90.0, endAngle: 95.0, dragon: '甲午'),
  DragonData(startAngle: 95.0, endAngle: 100.0, dragon: '乙未'),
  DragonData(startAngle: 100.0, endAngle: 105.0, dragon: '丙申'),
  DragonData(startAngle: 105.0, endAngle: 110.0, dragon: '丁酉'),
  DragonData(startAngle: 110.0, endAngle: 115.0, dragon: '戊戌'),
  DragonData(startAngle: 115.0, endAngle: 120.0, dragon: '己亥'),
  DragonData(startAngle: 120.0, endAngle: 125.0, dragon: '庚子'),
  DragonData(startAngle: 125.0, endAngle: 130.0, dragon: '辛丑'),
  DragonData(startAngle: 130.0, endAngle: 135.0, dragon: '壬寅'),
  DragonData(startAngle: 135.0, endAngle: 140.0, dragon: '癸卯'),
  DragonData(startAngle: 140.0, endAngle: 145.0, dragon: '甲辰'),
  DragonData(startAngle: 145.0, endAngle: 150.0, dragon: '乙巳'),
  DragonData(startAngle: 150.0, endAngle: 155.0, dragon: '丙午'),
  DragonData(startAngle: 155.0, endAngle: 160.0, dragon: '丁未'),
  DragonData(startAngle: 160.0, endAngle: 165.0, dragon: '戊申'),
  DragonData(startAngle: 165.0, endAngle: 170.0, dragon: '己酉'),
  DragonData(startAngle: 170.0, endAngle: 175.0, dragon: '庚戌'),
  DragonData(startAngle: 175.0, endAngle: 180.0, dragon: '辛亥'),
  DragonData(startAngle: 180.0, endAngle: 185.0, dragon: '壬子'),
  DragonData(startAngle: 185.0, endAngle: 190.0, dragon: '癸丑'),
  DragonData(startAngle: 190.0, endAngle: 195.0, dragon: '甲寅'),
  DragonData(startAngle: 195.0, endAngle: 200.0, dragon: '乙卯'),
  DragonData(startAngle: 200.0, endAngle: 205.0, dragon: '丙辰'),
  DragonData(startAngle: 205.0, endAngle: 210.0, dragon: '丁巳'),
  DragonData(startAngle: 210.0, endAngle: 215.0, dragon: '戊午'),
  DragonData(startAngle: 215.0, endAngle: 220.0, dragon: '己未'),
  DragonData(startAngle: 220.0, endAngle: 225.0, dragon: '庚申'),
  DragonData(startAngle: 225.0, endAngle: 230.0, dragon: '辛酉'),
  DragonData(startAngle: 230.0, endAngle: 235.0, dragon: '壬戌'),
  DragonData(startAngle: 235.0, endAngle: 240.0, dragon: '癸亥'),
  DragonData(startAngle: 240.0, endAngle: 245.0, dragon: '甲子'),
  DragonData(startAngle: 245.0, endAngle: 250.0, dragon: '乙丑'),
  DragonData(startAngle: 250.0, endAngle: 255.0, dragon: '丙寅'),
  DragonData(startAngle: 255.0, endAngle: 260.0, dragon: '丁卯'),
  DragonData(startAngle: 260.0, endAngle: 265.0, dragon: '戊辰'),
  DragonData(startAngle: 265.0, endAngle: 270.0, dragon: '己巳'),
  DragonData(startAngle: 270.0, endAngle: 275.0, dragon: '庚午'),
  DragonData(startAngle: 275.0, endAngle: 280.0, dragon: '辛未'),
  DragonData(startAngle: 280.0, endAngle: 285.0, dragon: '壬申'),
  DragonData(startAngle: 285.0, endAngle: 290.0, dragon: '癸酉'),
  DragonData(startAngle: 290.0, endAngle: 295.0, dragon: '甲戌'),
  DragonData(startAngle: 295.0, endAngle: 300.0, dragon: '乙亥'),
  DragonData(startAngle: 300.0, endAngle: 305.0, dragon: '丙子'),
  DragonData(startAngle: 305.0, endAngle: 310.0, dragon: '丁丑'),
  DragonData(startAngle: 310.0, endAngle: 315.0, dragon: '戊寅'),
  DragonData(startAngle: 315.0, endAngle: 320.0, dragon: '己卯'),
  DragonData(startAngle: 320.0, endAngle: 325.0, dragon: '庚辰'),
  DragonData(startAngle: 325.0, endAngle: 330.0, dragon: '辛巳'),
  DragonData(startAngle: 330.0, endAngle: 335.0, dragon: '壬午'),
  DragonData(startAngle: 335.0, endAngle: 340.0, dragon: '癸未'),
  DragonData(startAngle: 340.0, endAngle: 345.0, dragon: '甲申'),
  DragonData(startAngle: 345.0, endAngle: 350.0, dragon: '乙酉'),
  DragonData(startAngle: 350.0, endAngle: 355.0, dragon: '丙戌'),
  DragonData(startAngle: 355.0, endAngle: 360.0, dragon: '丁亥'),
];

const List<GoldData> goldDatas = [
  GoldData(startAngle: 0.0, endAngle: 3.0, gold: '丙子丙'),
  GoldData(startAngle: 3.0, endAngle: 6.0, gold: '丙子戊'),
  GoldData(startAngle: 6.0, endAngle: 9.0, gold: '丁丑丁'),
  GoldData(startAngle: 9.0, endAngle: 12.0, gold: '丁丑己'),
  GoldData(startAngle: 12.0, endAngle: 15.0, gold: '庚寅庚'),
  GoldData(startAngle: 15.0, endAngle: 18.0, gold: '庚寅壬'),
  GoldData(startAngle: 18.0, endAngle: 21.0, gold: '辛卯辛'),
  GoldData(startAngle: 21.0, endAngle: 24.0, gold: '辛卯癸'),
  GoldData(startAngle: 24.0, endAngle: 27.0, gold: '甲辰甲'),
  GoldData(startAngle: 27.0, endAngle: 30.0, gold: '甲辰丙'),
  GoldData(startAngle: 30.0, endAngle: 33.0, gold: '乙巳乙'),
  GoldData(startAngle: 33.0, endAngle: 36.0, gold: '乙巳丁'),
  GoldData(startAngle: 36.0, endAngle: 39.0, gold: '戊午戊'),
  GoldData(startAngle: 39.0, endAngle: 42.0, gold: '戊午庚'),
  GoldData(startAngle: 42.0, endAngle: 45.0, gold: '己未己'),
  GoldData(startAngle: 45.0, endAngle: 48.0, gold: '己未辛'),
  GoldData(startAngle: 48.0, endAngle: 51.0, gold: '壬申壬'),
  GoldData(startAngle: 51.0, endAngle: 54.0, gold: '壬申甲'),
  GoldData(startAngle: 54.0, endAngle: 57.0, gold: '癸酉癸'),
  GoldData(startAngle: 57.0, endAngle: 60.0, gold: '癸酉乙'),
  GoldData(startAngle: 60.0, endAngle: 63.0, gold: '丙戌丙'),
  GoldData(startAngle: 63.0, endAngle: 66.0, gold: '丙戌戊'),
  GoldData(startAngle: 66.0, endAngle: 69.0, gold: '丁亥丁'),
  GoldData(startAngle: 69.0, endAngle: 72.0, gold: '丁亥己'),
  GoldData(startAngle: 72.0, endAngle: 75.0, gold: '庚子庚'),
  GoldData(startAngle: 75.0, endAngle: 78.0, gold: '庚子壬'),
  GoldData(startAngle: 78.0, endAngle: 81.0, gold: '辛丑辛'),
  GoldData(startAngle: 81.0, endAngle: 84.0, gold: '辛丑癸'),
  GoldData(startAngle: 84.0, endAngle: 87.0, gold: '甲寅甲'),
  GoldData(startAngle: 87.0, endAngle: 90.0, gold: '甲寅丙'),
  GoldData(startAngle: 90.0, endAngle: 93.0, gold: '乙卯乙'),
  GoldData(startAngle: 93.0, endAngle: 96.0, gold: '乙卯丁'),
  GoldData(startAngle: 96.0, endAngle: 99.0, gold: '戊辰戊'),
  GoldData(startAngle: 99.0, endAngle: 102.0, gold: '戊辰庚'),
  GoldData(startAngle: 102.0, endAngle: 105.0, gold: '己巳己'),
  GoldData(startAngle: 105.0, endAngle: 108.0, gold: '己巳辛'),
  GoldData(startAngle: 108.0, endAngle: 111.0, gold: '壬午壬'),
  GoldData(startAngle: 111.0, endAngle: 114.0, gold: '壬午甲'),
  GoldData(startAngle: 114.0, endAngle: 117.0, gold: '癸未癸'),
  GoldData(startAngle: 117.0, endAngle: 120.0, gold: '癸未乙'),
  GoldData(startAngle: 120.0, endAngle: 123.0, gold: '丙申丙'),
  GoldData(startAngle: 123.0, endAngle: 126.0, gold: '丙申戊'),
  GoldData(startAngle: 126.0, endAngle: 129.0, gold: '丁酉丁'),
  GoldData(startAngle: 129.0, endAngle: 132.0, gold: '丁酉己'),
  GoldData(startAngle: 132.0, endAngle: 135.0, gold: '庚戌庚'),
  GoldData(startAngle: 135.0, endAngle: 138.0, gold: '庚戌壬'),
  GoldData(startAngle: 138.0, endAngle: 141.0, gold: '辛亥辛'),
  GoldData(startAngle: 141.0, endAngle: 144.0, gold: '辛亥癸'),
  GoldData(startAngle: 144.0, endAngle: 147.0, gold: '甲子甲'),
  GoldData(startAngle: 147.0, endAngle: 150.0, gold: '甲子丙'),
  GoldData(startAngle: 150.0, endAngle: 153.0, gold: '乙丑乙'),
  GoldData(startAngle: 153.0, endAngle: 156.0, gold: '乙丑丁'),
  GoldData(startAngle: 156.0, endAngle: 159.0, gold: '戊寅戊'),
  GoldData(startAngle: 159.0, endAngle: 162.0, gold: '戊寅庚'),
  GoldData(startAngle: 162.0, endAngle: 165.0, gold: '己卯己'),
  GoldData(startAngle: 165.0, endAngle: 168.0, gold: '己卯辛'),
  GoldData(startAngle: 168.0, endAngle: 171.0, gold: '壬辰壬'),
  GoldData(startAngle: 171.0, endAngle: 174.0, gold: '壬辰甲'),
  GoldData(startAngle: 174.0, endAngle: 177.0, gold: '癸巳癸'),
  GoldData(startAngle: 177.0, endAngle: 180.0, gold: '癸巳乙'),
  GoldData(startAngle: 180.0, endAngle: 183.0, gold: '丙午丙'),
  GoldData(startAngle: 183.0, endAngle: 186.0, gold: '丙午戊'),
  GoldData(startAngle: 186.0, endAngle: 189.0, gold: '丁未丁'),
  GoldData(startAngle: 189.0, endAngle: 192.0, gold: '丁未己'),
  GoldData(startAngle: 192.0, endAngle: 195.0, gold: '庚申庚'),
  GoldData(startAngle: 195.0, endAngle: 198.0, gold: '庚申壬'),
  GoldData(startAngle: 198.0, endAngle: 201.0, gold: '辛酉辛'),
  GoldData(startAngle: 201.0, endAngle: 204.0, gold: '辛酉癸'),
  GoldData(startAngle: 204.0, endAngle: 207.0, gold: '甲戌甲'),
  GoldData(startAngle: 207.0, endAngle: 210.0, gold: '甲戌丙'),
  GoldData(startAngle: 210.0, endAngle: 213.0, gold: '乙亥乙'),
  GoldData(startAngle: 213.0, endAngle: 216.0, gold: '乙亥丁'),
  GoldData(startAngle: 216.0, endAngle: 219.0, gold: '戊子戊'),
  GoldData(startAngle: 219.0, endAngle: 222.0, gold: '戊子庚'),
  GoldData(startAngle: 222.0, endAngle: 225.0, gold: '己丑己'),
  GoldData(startAngle: 225.0, endAngle: 228.0, gold: '己丑辛'),
  GoldData(startAngle: 228.0, endAngle: 231.0, gold: '壬寅壬'),
  GoldData(startAngle: 231.0, endAngle: 234.0, gold: '壬寅甲'),
  GoldData(startAngle: 234.0, endAngle: 237.0, gold: '癸卯癸'),
  GoldData(startAngle: 237.0, endAngle: 240.0, gold: '癸卯乙'),
  GoldData(startAngle: 240.0, endAngle: 243.0, gold: '丙辰丙'),
  GoldData(startAngle: 243.0, endAngle: 246.0, gold: '丙辰戊'),
  GoldData(startAngle: 246.0, endAngle: 249.0, gold: '丁巳丁'),
  GoldData(startAngle: 249.0, endAngle: 252.0, gold: '丁巳己'),
  GoldData(startAngle: 252.0, endAngle: 255.0, gold: '庚午庚'),
  GoldData(startAngle: 255.0, endAngle: 258.0, gold: '庚午壬'),
  GoldData(startAngle: 258.0, endAngle: 261.0, gold: '辛未辛'),
  GoldData(startAngle: 261.0, endAngle: 264.0, gold: '辛未癸'),
  GoldData(startAngle: 264.0, endAngle: 267.0, gold: '甲申甲'),
  GoldData(startAngle: 267.0, endAngle: 270.0, gold: '甲申丙'),
  GoldData(startAngle: 270.0, endAngle: 273.0, gold: '乙酉乙'),
  GoldData(startAngle: 273.0, endAngle: 276.0, gold: '乙酉丁'),
  GoldData(startAngle: 276.0, endAngle: 279.0, gold: '戊戌戊'),
  GoldData(startAngle: 279.0, endAngle: 282.0, gold: '戊戌庚'),
  GoldData(startAngle: 282.0, endAngle: 285.0, gold: '己亥己'),
  GoldData(startAngle: 285.0, endAngle: 288.0, gold: '己亥辛'),
  GoldData(startAngle: 288.0, endAngle: 291.0, gold: '壬子壬'),
  GoldData(startAngle: 291.0, endAngle: 294.0, gold: '壬子甲'),
  GoldData(startAngle: 294.0, endAngle: 297.0, gold: '癸丑癸'),
  GoldData(startAngle: 297.0, endAngle: 300.0, gold: '癸丑乙'),
  GoldData(startAngle: 300.0, endAngle: 303.0, gold: '丙寅丙'),
  GoldData(startAngle: 303.0, endAngle: 306.0, gold: '丙寅戊'),
  GoldData(startAngle: 306.0, endAngle: 309.0, gold: '丁卯丁'),
  GoldData(startAngle: 309.0, endAngle: 312.0, gold: '丁卯己'),
  GoldData(startAngle: 312.0, endAngle: 315.0, gold: '庚辰庚'),
  GoldData(startAngle: 315.0, endAngle: 318.0, gold: '庚辰壬'),
  GoldData(startAngle: 318.0, endAngle: 321.0, gold: '辛巳辛'),
  GoldData(startAngle: 321.0, endAngle: 324.0, gold: '辛巳癸'),
  GoldData(startAngle: 324.0, endAngle: 327.0, gold: '甲午甲'),
  GoldData(startAngle: 327.0, endAngle: 330.0, gold: '甲午丙'),
  GoldData(startAngle: 330.0, endAngle: 333.0, gold: '乙未乙'),
  GoldData(startAngle: 333.0, endAngle: 336.0, gold: '乙未丁'),
  GoldData(startAngle: 336.0, endAngle: 339.0, gold: '戊申戊'),
  GoldData(startAngle: 339.0, endAngle: 342.0, gold: '戊申庚'),
  GoldData(startAngle: 342.0, endAngle: 345.0, gold: '己酉己'),
  GoldData(startAngle: 345.0, endAngle: 348.0, gold: '己酉辛'),
  GoldData(startAngle: 348.0, endAngle: 351.0, gold: '壬戌壬'),
  GoldData(startAngle: 351.0, endAngle: 354.0, gold: '壬戌甲'),
  GoldData(startAngle: 354.0, endAngle: 357.0, gold: '癸亥癸'),
  GoldData(startAngle: 357.0, endAngle: 360.0, gold: '癸亥乙'),
];

const List<Renpan24Data> renpan24Datas = [
  Renpan24Data(startAngle: 345.0, endAngle: 0.0, mountain: '壬'),
  Renpan24Data(startAngle: 0.0, endAngle: 15.0, mountain: '子'),
  Renpan24Data(startAngle: 15.0, endAngle: 30.0, mountain: '癸'),
  Renpan24Data(startAngle: 30.0, endAngle: 45.0, mountain: '丑'),
  Renpan24Data(startAngle: 45.0, endAngle: 60.0, mountain: '艮'),
  Renpan24Data(startAngle: 60.0, endAngle: 75.0, mountain: '寅'),
  Renpan24Data(startAngle: 75.0, endAngle: 90.0, mountain: '甲'),
  Renpan24Data(startAngle: 90.0, endAngle: 105.0, mountain: '卯'),
  Renpan24Data(startAngle: 105.0, endAngle: 120.0, mountain: '乙'),
  Renpan24Data(startAngle: 120.0, endAngle: 135.0, mountain: '辰'),
  Renpan24Data(startAngle: 135.0, endAngle: 150.0, mountain: '巽'),
  Renpan24Data(startAngle: 150.0, endAngle: 165.0, mountain: '巳'),
  Renpan24Data(startAngle: 165.0, endAngle: 180.0, mountain: '丙'),
  Renpan24Data(startAngle: 180.0, endAngle: 195.0, mountain: '午'),
  Renpan24Data(startAngle: 195.0, endAngle: 210.0, mountain: '丁'),
  Renpan24Data(startAngle: 210.0, endAngle: 225.0, mountain: '未'),
  Renpan24Data(startAngle: 225.0, endAngle: 240.0, mountain: '坤'),
  Renpan24Data(startAngle: 240.0, endAngle: 255.0, mountain: '申'),
  Renpan24Data(startAngle: 255.0, endAngle: 270.0, mountain: '庚'),
  Renpan24Data(startAngle: 270.0, endAngle: 285.0, mountain: '酉'),
  Renpan24Data(startAngle: 285.0, endAngle: 300.0, mountain: '辛'),
  Renpan24Data(startAngle: 300.0, endAngle: 315.0, mountain: '戌'),
  Renpan24Data(startAngle: 315.0, endAngle: 330.0, mountain: '乾'),
  Renpan24Data(startAngle: 330.0, endAngle: 345.0, mountain: '亥'),
];
